version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: webpack
    versions:
    - 4.44.2
