language: node_js
node_js: "stable"
services:
  - mongodb
env:
  - NODE_ENV=travis

before_script:
  - mongo shassi --eval 'db.createUser({user:"admin", pwd:"admin", roles:["readWrite"]});'
script:
  - jest --coverage --coverageReporters=text-lcov | coveralls
  - npm run lint
  - npm run test:e2e
  - sonar-scanner
addons:
  sonarcloud:
    organization: "kiwikern-github"
    token: $SONAR_TOKEN
