language: node_js
node_js: "12.0.0"

cache: npm
env:
  - NODE_ENV=travis
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: jest
    - script: npm run lint
      name: "Lint"
    - script: npm run test:e2e
      name: "Integration Tests"
      services:
        - mongodb
      before_script: mongo shassi_ci --eval 'db.createUser({user:"admin", pwd:"admin", roles:["readWrite"]});'
    - stage: "Code Quality"
      name: "Sonarcloud"
      script:
        - npm run test:cov
        - sonar-scanner
      addons:
        sonarcloud:
          organization: "kiwikern-github"
          token: $SONAR_TOKEN
    - script: jest --coverage --coverageReporters=text-lcov | coveralls
      name: "Coveralls"
    - stage: "Deployment"
      name: "Deployment"
      before_install: echo 'Skip...'
      install: echo 'Skip...'
      script: echo 'Deploying...'
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: shassi
        on:
          tags: true

