language: node_js
node_js: "stable"
env:
  - NODE_ENV=travis
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: jest --coverage --coverageReporters=text-lcov | coveralls
    - script: npm run lint
      name: "Lint"
    - script: npm run test:e2e
      name: "Integration Tests"
      services:
        - mongodb
      before_script: mongo shassi_ci --eval 'db.createUser({user:"admin", pwd:"admin", roles:["readWrite"]});'
    - stage: "Sonarcloud"
      script:
        - npm run test:cov
        - sonar-scanner
      addons:
        sonarcloud:
          organization: "kiwikern-github"
          token: $SONAR_TOKEN

