import { AboutyouCrawler } from '../../src/crawler/crawlers/aboutyou.crawler';

export const aboutyouExtrasaleTestCase = {
  crawlerType: AboutyouCrawler,

  url: 'https://aboutyou-4708587',

  sizes: [
    { id: '39789330', isAvailable: false, name: '28' },
    { id: '39789331', isAvailable: true, name: '29' },
    { id: '39789332', isAvailable: true, name: '30' },
    { id: '39789333', isAvailable: true, name: '31' },
    { id: '39789334', isAvailable: true, name: '32' },
    { id: '39789335', isAvailable: true, name: '33' },
    { id: '39789336', isAvailable: true, name: '34' },
    { id: '39789337', isAvailable: true, name: '36' },
    { id: '39789338', isAvailable: false, name: '38' },
  ],

  sizeChecks: [
    { size: '39789338', isAvailable: false, isLowInStock: false },
    { size: '39789337', isAvailable: true, isLowInStock: true },
    { size: 'sizedoesnotexist', isAvailable: false, isLowInStock: false },
  ],

  name: "Only & Sons - Shorts '5274'",

  priceChecks: [
    { size: '39789337', price: 26.99 },
    { size: '39789331', price: 21.9 },
  ],

  testResponse: {
    pagination: {
      current: 1,
      total: 1,
      perPage: 100,
      page: 1,
      first: 1,
      prev: 1,
      next: 1,
      last: 1,
    },
    entities: [
      {
        id: 4708587,
        isActive: true,
        isSoldOut: false,
        isNew: false,
        createdAt: '2020-03-23T16:29:34+01:00',
        updatedAt: '2020-04-03T08:22:54+02:00',
        masterKey: '321353-120',
        referenceKey: '22015274-GreyDenim',
        attributes: {
          plusSize: {
            id: 315,
            key: 'plusSize',
            label: 'Plus Size',
            type: '',
            multiSelect: false,
            values: { id: 35002, label: 'nein', value: '0' },
          },
          brand: {
            id: 550,
            key: 'brand',
            label: 'Marke',
            type: '',
            multiSelect: false,
            values: { id: 6459, label: 'Only & Sons', value: 'only_sons' },
          },
          colorDetail: {
            id: 210,
            key: 'colorDetail',
            label: 'Detailfarbe',
            type: '',
            multiSelect: true,
            values: [{ id: 38805, label: 'grau', value: 'grau' }],
          },
          brandLogo: {
            id: 20000,
            key: 'brandLogo',
            label: 'Brand logo',
            type: '',
            multiSelect: false,
            values: {
              id: 6459,
              label: 'Only & Sons',
              value: '001124b1983d0bb3079952320724372e',
            },
          },
          name: {
            id: 20005,
            key: 'name',
            label: 'Name',
            type: null,
            multiSelect: false,
            values: { label: "Shorts '5274'" },
          },
        },
        images: [
          { hash: 'e79256c0407cc743b1116362cadd6b28' },
          { hash: '4cc2310cc7c7fd8cc4e79b09ccfad8ee' },
          { hash: '99c2c72be04979281310cb806c2c647d' },
          { hash: 'f2b79ec4e07940142cb2463a35e72c5e' },
          { hash: 'cd1cd16a411aaf1b50ad95ffbc67a4bb' },
          { hash: '0fbc9c397c58c1c5c21a6cde7fe316f1' },
          { hash: 'ac32299c27a65e29814e4e11467d05d2' },
        ],
        variants: [
          {
            id: 39789330,
            referenceKey: 'ONS1606001000001',
            createdAt: '2020-03-23T16:29:34+01:00',
            updatedAt: '2020-05-17T06:41:41+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25497, label: '28', value: '28' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41073, label: '300', value: '300' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41349, label: '28', value: '28' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41352, label: '28', value: '28' }],
              },
            },
          },
          {
            id: 39789331,
            referenceKey: 'ONS1606001000002',
            createdAt: '2020-03-23T16:29:34+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 15,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25502, label: '29', value: '29' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41196, label: '350', value: '350' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41361, label: '29', value: '29' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41364, label: '29', value: '29' }],
              },
            },
          },
          {
            id: 39789332,
            referenceKey: 'ONS1606001000003',
            createdAt: '2020-03-23T16:29:34+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 23,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25511, label: '30', value: '30' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41085, label: '400', value: '400' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41373, label: '30', value: '30' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41376, label: '30', value: '30' }],
              },
            },
          },
          {
            id: 39789333,
            referenceKey: 'ONS1606001000004',
            createdAt: '2020-03-23T16:29:34+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 41,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25532, label: '31', value: '31' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41160, label: '450', value: '450' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41385, label: '31', value: '31' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41388, label: '31', value: '31' }],
              },
            },
          },
          {
            id: 39789334,
            referenceKey: 'ONS1606001000005',
            createdAt: '2020-03-23T16:29:35+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 42,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25521, label: '32', value: '32' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41097, label: '500', value: '500' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41397, label: '32', value: '32' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41400, label: '32', value: '32' }],
              },
            },
          },
          {
            id: 39789335,
            referenceKey: 'ONS1606001000006',
            createdAt: '2020-03-23T16:29:35+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 48,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25524, label: '33', value: '33' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41172, label: '550', value: '550' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41850, label: '33', value: '33' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41853, label: '33', value: '33' }],
              },
            },
          },
          {
            id: 39789336,
            referenceKey: 'ONS1606001000007',
            createdAt: '2020-03-23T16:29:35+01:00',
            updatedAt: '2020-05-17T03:36:17+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2190,
              withoutTax: 1840,
              appliedReductions: [
                {
                  category: 'sale',
                  type: 'relative',
                  amount: { relative: 0.19, absoluteWithTax: 500 },
                },
              ],
              tax: { vat: { amount: 350, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 5,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25472, label: '34', value: '34' },
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41109, label: '600', value: '600' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41262, label: '34', value: '34' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41265, label: '34', value: '34' }],
              },
            },
          },
          {
            id: 39789337,
            referenceKey: '5714508960128',
            createdAt: '2020-03-23T16:29:35+01:00',
            updatedAt: '2020-05-17T15:35:03+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2699,
              withoutTax: 2268,
              appliedReductions: [],
              tax: { vat: { amount: 431, rate: 0.19 } },
            },
            stock: {
              supplierId: 120,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25474, label: '36', value: '36' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41049, label: '36', value: '36' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41052, label: '36', value: '36' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41211, label: '700', value: '700' },
              },
            },
          },
          {
            id: 39789338,
            referenceKey: '5714508960135',
            createdAt: '2020-03-23T16:29:35+01:00',
            updatedAt: '2020-05-17T06:41:50+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 2699,
              withoutTax: 2268,
              appliedReductions: [],
              tax: { vat: { amount: 431, rate: 0.19 } },
            },
            stock: {
              supplierId: 120,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25471, label: '38', value: '38' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41067, label: '38', value: '38' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41070, label: '38', value: '38' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41232, label: '800', value: '800' },
              },
            },
          },
        ],
      },
    ],
  },
};
