import { AboutyouCrawler } from '../../src/crawler/crawlers/aboutyou.crawler';

export const aboutyouSizeWithLengthTestCase = {
  crawlerType: AboutyouCrawler,

  url: 'https://www.aboutyou.de/p/levi-s/jeans-511-3634233',

  sizes: [
    { id: '33623654', isAvailable: true, name: '36/34' },
    { id: '33623655', isAvailable: true, name: '38/34' },
    { id: '33623656', isAvailable: false, name: '31/34' },
    { id: '33623657', isAvailable: true, name: '32/34' },
    { id: '33623658', isAvailable: true, name: '33/34' },
    { id: '33623659', isAvailable: false, name: '34/34' },
    { id: '33623660', isAvailable: true, name: '30/34' },
    { id: '33623661', isAvailable: false, name: '33/32' },
    { id: '33623662', isAvailable: false, name: '34/32' },
    { id: '33623663', isAvailable: false, name: '36/32' },
    { id: '33623664', isAvailable: true, name: '38/32' },
    { id: '33623665', isAvailable: true, name: '30/32' },
    { id: '33623666', isAvailable: true, name: '31/32' },
    { id: '33623667', isAvailable: true, name: '32/32' },
    { id: '33623668', isAvailable: true, name: '31/30' },
    { id: '33623669', isAvailable: false, name: '32/30' },
    { id: '33623670', isAvailable: true, name: '33/30' },
    { id: '33623671', isAvailable: false, name: '34/30' },
    { id: '33623672', isAvailable: false, name: '36/30' },
    { id: '33623673', isAvailable: true, name: '30/30' },
    { id: '33949416', isAvailable: true, name: '29/30' },
    { id: '33949417', isAvailable: true, name: '29/32' },
    { id: '37420038', isAvailable: true, name: '27/30' },
    { id: '37420039', isAvailable: true, name: '27/32' },
    { id: '37420040', isAvailable: true, name: '28/30' },
    { id: '37420041', isAvailable: false, name: '28/32' },
    { id: '37420042', isAvailable: true, name: '29/34' },
    { id: '37420043', isAvailable: true, name: '32/36' },
    { id: '37420044', isAvailable: true, name: '33/36' },
    { id: '37420045', isAvailable: true, name: '34/36' },
    { id: '37420046', isAvailable: true, name: '36/36' },
    { id: '37420047', isAvailable: false, name: '38/30' },
    { id: '37420053', isAvailable: true, name: '40/32' },
    { id: '37420054', isAvailable: true, name: '40/34' },
  ],

  sizeChecks: [
    { size: '33623673', isAvailable: true, isLowInStock: true },
    { size: '37420047', isAvailable: false, isLowInStock: false },
    { size: 'sizedoesnotexist', isAvailable: false, isLowInStock: false },
  ],

  name: "LEVI'S - Jeans '511'",

  priceChecks: [
    { size: '33623673', price: 99.9 },
    { size: '37420047', price: 99.9 },
  ],

  testResponse: {
    pagination: {
      current: 1,
      total: 1,
      perPage: 100,
      page: 1,
      first: 1,
      prev: 1,
      next: 1,
      last: 1,
    },
    entities: [
      {
        id: 3634233,
        isActive: true,
        isSoldOut: false,
        isNew: false,
        createdAt: '2017-05-22T10:41:47+02:00',
        updatedAt: '2020-03-02T14:00:53+01:00',
        masterKey: 'LEV0008-5',
        referenceKey: 'NTUxOTExMzAwbmlnaHRzaGluZQ==',
        attributes: {
          colorDetail: {
            id: 210,
            key: 'colorDetail',
            label: 'Detailfarbe',
            type: '',
            multiSelect: true,
            values: [{ id: 38906, label: 'black denim', value: 'black_denim' }],
          },
          plusSize: {
            id: 315,
            key: 'plusSize',
            label: 'Plus Size',
            type: '',
            multiSelect: false,
            values: { id: 35002, label: 'nein', value: '0' },
          },
          brand: {
            id: 550,
            key: 'brand',
            label: 'Marke',
            type: '',
            multiSelect: false,
            values: { id: 226, label: "LEVI'S", value: 'levis' },
          },
          brandLogo: {
            id: 20000,
            key: 'brandLogo',
            label: 'Brand logo',
            type: '',
            multiSelect: false,
            values: {
              id: 226,
              label: "LEVI'S",
              value: 'a5e00bc8780d024830c5dc3448d45286',
            },
          },
          name: {
            id: 20005,
            key: 'name',
            label: 'Name',
            type: null,
            multiSelect: false,
            values: { label: "Jeans '511'" },
          },
        },
        images: [
          { hash: '15e583f376f1bc06f3a39d9b17165f5b' },
          { hash: '04287b7bc99c5d378cf3cf90e29f40b6' },
          { hash: '982127260a9c0f22ac913635ee3c6763' },
          { hash: '2fe5879f740cfcbc213c4d57d73a687f' },
          { hash: '4c966387b96f5a008eeb60b1b1fb29a2' },
          { hash: '0c364b3142afcff92a5db2d26b244550' },
          { hash: '99125acb8ccedc883acc9c284ea87a76' },
          { hash: 'e02987264acdcb5341509d9efb6784d8' },
          { hash: '2d15817f3b8a34bdc1455417cc0ff6b4' },
          { hash: 'a567fc0b828c1697e0c992dc652988e4' },
        ],
        variants: [
          {
            id: 33623654,
            referenceKey: 'KH96127613634',
            createdAt: '2017-05-22T10:41:47+02:00',
            updatedAt: '2020-05-17T11:05:24+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25474, label: '36', value: '36' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41049, label: '36', value: '36' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41052, label: '36', value: '36' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41211, label: '700', value: '700' },
              },
            },
          },
          {
            id: 33623655,
            referenceKey: 'LEV0008008000031',
            createdAt: '2017-05-22T10:41:47+02:00',
            updatedAt: '2020-05-16T11:10:24+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25471, label: '38', value: '38' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41067, label: '38', value: '38' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41070, label: '38', value: '38' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41232, label: '800', value: '800' },
              },
            },
          },
          {
            id: 33623656,
            referenceKey: 'LEV0008008000008',
            createdAt: '2017-05-22T10:41:47+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25532, label: '31', value: '31' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41385, label: '31', value: '31' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41388, label: '31', value: '31' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41160, label: '450', value: '450' },
              },
            },
          },
          {
            id: 33623657,
            referenceKey: 'LEV0008008000011',
            createdAt: '2017-05-22T10:41:47+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25521, label: '32', value: '32' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41397, label: '32', value: '32' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41400, label: '32', value: '32' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41097, label: '500', value: '500' },
              },
            },
          },
          {
            id: 33623658,
            referenceKey: 'KH96127613334',
            createdAt: '2017-05-22T10:41:47+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 10,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25524, label: '33', value: '33' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41850, label: '33', value: '33' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41853, label: '33', value: '33' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41172, label: '550', value: '550' },
              },
            },
          },
          {
            id: 33623659,
            referenceKey: 'LEV0008008000016',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25472, label: '34', value: '34' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41262, label: '34', value: '34' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41265, label: '34', value: '34' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41109, label: '600', value: '600' },
              },
            },
          },
          {
            id: 33623660,
            referenceKey: 'LEV0008008000005',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T06:20:59+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25511, label: '30', value: '30' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41373, label: '30', value: '30' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41376, label: '30', value: '30' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41085, label: '400', value: '400' },
              },
            },
          },
          {
            id: 33623661,
            referenceKey: 'LEV0008008000013',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25524, label: '33', value: '33' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41850, label: '33', value: '33' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41853, label: '33', value: '33' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41172, label: '550', value: '550' },
              },
            },
          },
          {
            id: 33623662,
            referenceKey: 'LEV0008008000015',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25472, label: '34', value: '34' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41262, label: '34', value: '34' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41265, label: '34', value: '34' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41109, label: '600', value: '600' },
              },
            },
          },
          {
            id: 33623663,
            referenceKey: 'LEV0008008000017',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T06:21:40+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25474, label: '36', value: '36' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41049, label: '36', value: '36' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41052, label: '36', value: '36' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41211, label: '700', value: '700' },
              },
            },
          },
          {
            id: 33623664,
            referenceKey: 'LEV0008008000030',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-15T15:18:29+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25471, label: '38', value: '38' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41067, label: '38', value: '38' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41070, label: '38', value: '38' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41232, label: '800', value: '800' },
              },
            },
          },
          {
            id: 33623665,
            referenceKey: 'KH96127613032',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 5,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25511, label: '30', value: '30' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41373, label: '30', value: '30' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41376, label: '30', value: '30' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41085, label: '400', value: '400' },
              },
            },
          },
          {
            id: 33623666,
            referenceKey: 'LEV0008008000007',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T06:21:00+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25532, label: '31', value: '31' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41385, label: '31', value: '31' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41388, label: '31', value: '31' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41160, label: '450', value: '450' },
              },
            },
          },
          {
            id: 33623667,
            referenceKey: 'LEV0008008000010',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25521, label: '32', value: '32' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41397, label: '32', value: '32' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41400, label: '32', value: '32' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41097, label: '500', value: '500' },
              },
            },
          },
          {
            id: 33623668,
            referenceKey: 'LEV0008008000006',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T06:21:00+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25532, label: '31', value: '31' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41385, label: '31', value: '31' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41388, label: '31', value: '31' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41160, label: '450', value: '450' },
              },
            },
          },
          {
            id: 33623669,
            referenceKey: 'LEV0008008000009',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25521, label: '32', value: '32' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41397, label: '32', value: '32' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41400, label: '32', value: '32' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41097, label: '500', value: '500' },
              },
            },
          },
          {
            id: 33623670,
            referenceKey: 'KH96127613330',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 5,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25524, label: '33', value: '33' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41850, label: '33', value: '33' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41853, label: '33', value: '33' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41172, label: '550', value: '550' },
              },
            },
          },
          {
            id: 33623671,
            referenceKey: 'LEV0008008000025',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T06:21:39+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25472, label: '34', value: '34' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41262, label: '34', value: '34' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41265, label: '34', value: '34' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41109, label: '600', value: '600' },
              },
            },
          },
          {
            id: 33623672,
            referenceKey: 'LEV0008008000027',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25474, label: '36', value: '36' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41049, label: '36', value: '36' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41052, label: '36', value: '36' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41211, label: '700', value: '700' },
              },
            },
          },
          {
            id: 33623673,
            referenceKey: 'KH96127613030',
            createdAt: '2017-05-22T10:41:48+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25511, label: '30', value: '30' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41373, label: '30', value: '30' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41376, label: '30', value: '30' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41085, label: '400', value: '400' },
              },
            },
          },
          {
            id: 33949416,
            referenceKey: 'LEV0008008000001',
            createdAt: '2017-08-17T13:04:45+02:00',
            updatedAt: '2020-05-15T15:18:23+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25502, label: '29', value: '29' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41361, label: '29', value: '29' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41364, label: '29', value: '29' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41196, label: '350', value: '350' },
              },
            },
          },
          {
            id: 33949417,
            referenceKey: 'LEV0008008000002',
            createdAt: '2017-08-17T13:04:45+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25502, label: '29', value: '29' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41361, label: '29', value: '29' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41364, label: '29', value: '29' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41196, label: '350', value: '350' },
              },
            },
          },
          {
            id: 37420038,
            referenceKey: 'LEV0008008000019',
            createdAt: '2019-05-24T09:29:14+02:00',
            updatedAt: '2020-05-15T15:18:27+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25499, label: '27', value: '27' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41337, label: '27', value: '27' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41340, label: '27', value: '27' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41280, label: '250', value: '250' },
              },
            },
          },
          {
            id: 37420039,
            referenceKey: 'LEV0008008000020',
            createdAt: '2019-05-24T09:29:15+02:00',
            updatedAt: '2020-05-15T15:18:27+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25499, label: '27', value: '27' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41337, label: '27', value: '27' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41340, label: '27', value: '27' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41280, label: '250', value: '250' },
              },
            },
          },
          {
            id: 37420040,
            referenceKey: 'LEV0008008000021',
            createdAt: '2019-05-24T09:29:15+02:00',
            updatedAt: '2020-05-15T15:18:27+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25497, label: '28', value: '28' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41349, label: '28', value: '28' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41352, label: '28', value: '28' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41073, label: '300', value: '300' },
              },
            },
          },
          {
            id: 37420041,
            referenceKey: 'LEV0008008000022',
            createdAt: '2019-05-24T09:29:15+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25497, label: '28', value: '28' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41349, label: '28', value: '28' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41352, label: '28', value: '28' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41073, label: '300', value: '300' },
              },
            },
          },
          {
            id: 37420042,
            referenceKey: 'LEV0008008000023',
            createdAt: '2019-05-24T09:29:15+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25502, label: '29', value: '29' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41361, label: '29', value: '29' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41364, label: '29', value: '29' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41196, label: '350', value: '350' },
              },
            },
          },
          {
            id: 37420043,
            referenceKey: 'KH96127613236',
            createdAt: '2019-05-24T09:29:16+02:00',
            updatedAt: '2020-05-17T05:48:47+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 5,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25521, label: '32', value: '32' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 27635, label: '36', value: '36' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41397, label: '32', value: '32' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41400, label: '32', value: '32' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41097, label: '500', value: '500' },
              },
            },
          },
          {
            id: 37420044,
            referenceKey: 'LEV0008008000024',
            createdAt: '2019-05-24T09:29:16+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25524, label: '33', value: '33' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 27635, label: '36', value: '36' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41850, label: '33', value: '33' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41853, label: '33', value: '33' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41172, label: '550', value: '550' },
              },
            },
          },
          {
            id: 37420045,
            referenceKey: 'LEV0008008000026',
            createdAt: '2019-05-24T09:29:16+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 2,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25472, label: '34', value: '34' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 27635, label: '36', value: '36' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41262, label: '34', value: '34' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41265, label: '34', value: '34' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41109, label: '600', value: '600' },
              },
            },
          },
          {
            id: 37420046,
            referenceKey: 'KH96127613636',
            createdAt: '2019-05-24T09:29:17+02:00',
            updatedAt: '2020-05-17T05:48:48+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 166,
              quantity: 3,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25474, label: '36', value: '36' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 27635, label: '36', value: '36' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41049, label: '36', value: '36' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41052, label: '36', value: '36' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41211, label: '700', value: '700' },
              },
            },
          },
          {
            id: 37420047,
            referenceKey: 'LEV0008008000029',
            createdAt: '2019-05-24T09:29:17+02:00',
            updatedAt: '2020-05-17T01:32:51+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 0,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25471, label: '38', value: '38' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25959, label: '30', value: '30' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41067, label: '38', value: '38' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41070, label: '38', value: '38' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41232, label: '800', value: '800' },
              },
            },
          },
          {
            id: 37420053,
            referenceKey: 'LEV0008008000032',
            createdAt: '2019-05-24T09:29:18+02:00',
            updatedAt: '2020-05-15T15:18:29+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 3,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25470, label: '40', value: '40' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25960, label: '32', value: '32' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41079, label: '40', value: '40' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41082, label: '40', value: '40' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41244, label: '850', value: '850' },
              },
            },
          },
          {
            id: 37420054,
            referenceKey: 'LEV0008008000033',
            createdAt: '2019-05-24T09:29:18+02:00',
            updatedAt: '2020-05-15T15:18:30+02:00',
            price: {
              currencyCode: 'EUR',
              withTax: 9990,
              withoutTax: 8395,
              appliedReductions: [],
              tax: { vat: { amount: 1595, rate: 0.19 } },
            },
            stock: {
              supplierId: 130,
              quantity: 1,
              isSellableWithoutStock: false,
            },
            attributes: {
              vendorSize: {
                id: 2,
                key: 'vendorSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 25470, label: '40', value: '40' },
              },
              length: {
                id: 5,
                key: 'length',
                label: 'Hosenbeinl\u00e4nge',
                type: '',
                multiSelect: false,
                values: { id: 25961, label: '34', value: '34' },
              },
              shopSize: {
                id: 8,
                key: 'shopSize',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: false,
                values: { id: 41079, label: '40', value: '40' },
              },
              categoryShopFilterSizes: {
                id: 9,
                key: 'categoryShopFilterSizes',
                label: 'Gr\u00f6\u00dfe',
                type: '',
                multiSelect: true,
                values: [{ id: 41082, label: '40', value: '40' }],
              },
              sort: {
                id: 10,
                key: 'sort',
                label: 'Sortierung',
                type: '',
                multiSelect: false,
                values: { id: 41244, label: '850', value: '850' },
              },
            },
          },
        ],
      },
    ],
  },
};
